[package]
name = "talker"
version = "0.1.0"
authors = ["gndl"]

[dependencies]
failure = "0.1.8"
lv2-sys = "2"
lv2_raw = "0.2"
livi = { git = "https://github.com/gndl/livi-rs.git", branch = "lilv_state", version = "0.7.5" }
#suil-sys = { git = "https://github.com/gndl/suil-sys.git" }
